export const incharge = [
    "INFORMATION OFFICER",
    "HAZARD ANALYST",
    "DEOC",
    "RISK CONTROLLING OFFICER(DEPUTY COLLECTOR)",
    "RESPONSIBLE OFFICER(DISTRICT COLLECTOR)",
    "SECURITY TEAM",
    "RESCUE TEAM",
    "TRANSPORT & SAFETY",
    "MEDICAL AID",
    "INFORMATION & MEDIA",
    "Circle Inspector of Police",
    "Station Officer, Fire & Rescue",
    "Motor Vehicle Inspector",
    "Medical Officer",
    "INFORMATION & MEDIA",
    "DISPLAY",
    "SPEAKERS",
]